### ISSUE TITLE
NoSuchMethodError: No static method 'from' declared in class 'List'.

### ISSUE THREAD

**Issue by putraxor** [renefloor/flutter_cache_manager#10]
From  ` cached_network_image: ^0.4.0` [cached_network_image](https://pub.dartlang.org/packages/cached_network_image)
```
E/flutter (14365): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (14365): NoSuchMethodError: No static method 'from' declared in class 'List'.
E/flutter (14365): Receiver: List
E/flutter (14365): Tried calling: from(Instance of 'WhereIterable')
E/flutter (14365): #0      NoSuchMethodError._throwNew (dart:core-patch/dart:core/errors_patch.dart:192)
E/flutter (14365): #1      CacheManager._removeOldObjectsFromCache (package:flutter_cache_manager/flutter_cache_manager.dart:149:26)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #2      CacheManager._cleanCache.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:135:15)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #3      SynchronizedLock._runTask.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:189:29)
E/flutter (14365): #4      _rootRun (dart:async/zone.dart:1126)
E/flutter (14365): #5      _CustomZone.run (dart:async/zone.dart:1023)
E/flutter (14365): #6      runZoned (dart:async/zone.dart:1501)
E/flutter (14365): #7      SynchronizedLock._runTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:187:14)
E/flutter (14365): #8      new Future.sync (dart:async/future.dart:222)
E/flutter (14365): #9      SynchronizedLock._runTask (package:synchronized/src/synchronized_impl.dart:186:16)
E/flutter (14365): #10     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:61:14)
E/flutter (14365): #11     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:71:17)
E/flutter (14365): #12     SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:222:12)
E/flutter (14365): #13     synchronized (package:synchronized/src/synchronized_impl.dart:284:19)
E/flutter (14365): #14     synchronized (package:synchronized/synchronized.dart:47:10)
E/flutter (14365): #15     CacheManager._cleanCache (package:flutter_cache_manager/flutter_cache_manager.dart:134:13)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #16     CacheManager._save (package:flutter_cache_manager/flutter_cache_manager.dart:75:11)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #17     CacheManager.getFile (package:flutter_cache_manager/flutter_cache_manager.dart:243:5)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #18     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:474:35)
E/flutter (14365): <asynchronous suspension>
E/flutter (14365): #19     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:462:16)
E/flutter (14365): #20     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
E/flutter (14365): #21     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
E/flutter (14365): #22     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
E/flutter (14365): #23     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
E/flutter (14365): #24     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:263:30)
E/flutter (14365): #25     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:239:55)
E/flutter (14365): #26     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:397:19)
E/flutter (14365): #27     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:415:5)
E/flutter (14365): #28     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1850:16)
E/flutter (14365): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2018:7)
E/flutter (14365): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:130:13)
E/flutter (14365): #31     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125:15)
E/flutter (14365): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2018:7)
E/flutter (14365): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:130:13)
E/flutter (14365): #34     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
E/flutter (14365): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2018:7)
E/flutter (14365): #36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:130:13)
E/flutter (14365): #37     RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:125:15)
E/flutter (14365): #38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2018:7)
E/flutter (14365): #39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:13
```

**Comment by renefloor** [comment]
```
    //Remove old objects
    var oldValues = List.from(
        _cacheData.values.where((c) => c.touched.isBefore(oldestDateAllowed)));
```
I am not sure if the error means that `List.from` doesn't exist anymore or that `_cacheData.values.where` just returns no items and that it doesn't work with that.

**Comment by putraxor** [comment]
In my opinion this issue comes from dart 2 preview, [new/const option] is too risky, maybe this plugin should new/const keyword until dart 2 stable

**Comment by jonasbark** [comment]
I agree with @putraxor. Using new fixed it for me. 
Is there a reason to not use .toList() instead of List.from()?
