### ISSUE TITLE
Unsupported operation: Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by long1eu** [renefloor/flutter_cache_manager#13]
```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES ╞══════════════════════════════════════════════════════════════════
flutter: The following UnsupportedError was thrown resolving an image codec:
flutter: Unsupported operation: Cannot set value in unmodifiable Map
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _ImmutableMap.[]= (dart:core/runtime/libimmutable_map.dart:78:5)
flutter: #1      CacheManager._downloadFile (package:flutter_cache_manager/flutter_cache_manager.dart:268:14)
flutter: <asynchronous suspension>
flutter: #2      CacheManager.getFile.<anonymous closure> (package:flutter_cache_manager/flutter_cache_manager.dart:236:34)
flutter: <asynchronous suspension>
flutter: #3      SynchronizedLock._runTask.<anonymous closure>.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:189:29)
flutter: #7      SynchronizedLock._runTask.<anonymous closure> (package:synchronized/src/synchronized_impl.dart:187:14)
flutter: #9      SynchronizedLock._runTask (package:synchronized/src/synchronized_impl.dart:186:16)
flutter: #10     LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:61:14)
flutter: #11     LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:71:17)
flutter: #12     SynchronizedLock.synchronized (package:synchronized/src/synchronized_impl.dart:222:12)
flutter: #13     synchronized (package:synchronized/src/synchronized_impl.dart:284:19)
flutter: #14     synchronized (package:synchronized/synchronized.dart:47:15)
flutter: #15     CacheManager.getFile (package:flutter_cache_manager/flutter_cache_manager.dart:199:11)
flutter: <asynchronous suspension>
flutter: #16     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:472:35)
flutter: <asynchronous suspension>
flutter: #17     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:462:16)
flutter: #18     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:86)
flutter: #19     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:82:22)
flutter: #20     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:265:63)
flutter: #21     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
flutter: #22     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:263:30)
flutter: #23     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:239:55)
flutter: #24     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:397:19)
flutter: #25     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:415:5)

```

**Comment by long1eu** [comment]
I got this on the cached network image package. So I don't know which version of the manager it uses.

**Comment by renefloor** [comment]
Sorry, I also meant the version of cached network image.

**Comment by long1eu** [comment]
0.4.1

**Comment by renefloor** [comment]
I'll have a look at it

**Comment by renefloor** [comment]
I see I left a mistake in CachedNetworkImageProvider. Are you using that directly? I cannot fix it right now, but will do it soon. As a workaround for now you can set `headers: new Map()`.
