### ISSUE TITLE
DatabaseException 

### ISSUE THREAD

**Issue by Fuxingloh** [renefloor/flutter_cache_manager#60]
I am using 0.3.0-alpha.2 & cached_network_image 0.6.0-alpha.2.

I consistently get DatabaseException(database_closed) exception off and on during development. Once I get this exception, all the images will subsequently fail to load.

```
E/flutter (20733): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (20733): DatabaseException(database_closed 17)
E/flutter (20733): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #1      SqfliteDatabase.txnRawQuery.<anonymous closure> (package:sqflite/src/database.dart:330:14)
E/flutter (20733): #2      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter (20733): #3      Lock._runTask (package:synchronized/src/synchronized_impl.dart:149:27)
E/flutter (20733): #4      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:64:14)
E/flutter (20733): #5      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:74:17)
E/flutter (20733): #6      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:142:12)
E/flutter (20733): #7      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:275:37)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #8      SqfliteDatabase.txnRawQuery (package:sqflite/src/database.dart:329:12)
E/flutter (20733): #9      SqfliteDatabaseExecutor.rawQuery (package:sqflite/src/database.dart:92:10)
E/flutter (20733): #10     SqfliteDatabaseExecutor.query (package:sqflite/src/database.dart:86:12)
E/flutter (20733): #11     CacheObjectProvider.get (package:flutter_cache_manager/src/cache_object.dart:100:31)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #12     CacheStore._getCacheDataFromDatabase (package:flutter_cache_manager/src/cache_store.dart:84:31)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #13     CacheStore.retrieveCacheData (package:flutter_cache_manager/src/cache_store.dart:63:7)
E/flutter (20733): #14     CacheStore.getFile (package:flutter_cache_manager/src/cache_store.dart:46:29)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #15     BaseCacheManager.getFileFromCache (package:flutter_cache_manager/src/cache_manager.dart:128:24)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #16     BaseCacheManager.getSingleFile (package:flutter_cache_manager/src/cache_manager.dart:89:27)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #17     CachedNetworkImageProvider._loadAsync (package:cached_network_image/cached_network_image.dart:482:27)
E/flutter (20733): <asynchronous suspension>
E/flutter (20733): #18     CachedNetworkImageProvider.load (package:cached_network_image/cached_network_image.dart:472:16)
E/flutter (20733): #19     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:86)
E/flutter (20733): #20     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
E/flutter (20733): #21     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:63)
E/flutter (20733): #22     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
E/flutter (20733): #23     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:265:30)
E/flutter (20733): #24     _ImageProviderResolver.resolve (package:cached_network_image/cached_network_image.dart:197:29)
E/flutter (20733): #25     _CachedNetworkImageState._resolveImage (package:cached_network_image/cached_network_image.dart:292:20)
E/flutter (20733): #26     _CachedNetworkImageState.didChangeDependencies (package:cached_network_image/cached_network_image.dart:267:5)
E/flutter (20733): #27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
E/flutter (20733): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (20733): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20733): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20733): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (20733): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (20733): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (20733): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (20733): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20733): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20733): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (20733): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (20733): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (20733): #40     SingleChildRenderObjectElement.mount (package
```

**Comment by hpoul** [comment]
FWIW, it seems this happens when there are "many" requests started at the same time.. imho `cache_store.dart` looks like having pretty bad race conditions. (e.g. `_openDatabaseConnection`: `if (_nrOfDbConnections == 0) { await provider.open(); } _nrOfDbConnections++;` would imho always produce multiple `open` calls since provider.open() does quite a bit of work in the background)

also, i think it's not really the best way to constantly open/close short lived sqlite connections, but rather just keep one connection open the whole time (see e.g. http://touchlabblog.tumblr.com/post/24474750219/single-sqlite-connection). Sqflite also has a guide on how to open the database without race conditions: https://github.com/tekartik/sqflite/blob/master/doc/opening_db.md#prevent-database-locked-issue

@renefloor are you open for PRs, or is this alpha version still too much in flux?

**Comment by renefloor** [comment]
@hpoul I indeed want to keep the database open for as long as possible, but I thought it would be better to close the connection when you close the app. However, there is no callback for when the app closes. Therefore I chose to close when there is no connection needed.

Pull request are very much appreciated with a good explanation of how it fixes the problem.

**Comment by davidmartos96** [comment]
I am also experiencing this error. Is anyone working on fixing it through a PR?

**Comment by renefloor** [comment]
(I think) I fixed it in https://github.com/renefloor/flutter_cache_manager/commit/5721c896f559998b544e5b9264880fb6561fb8cb
