### ISSUE TITLE
cannot getDatabasePath

### ISSUE THREAD

**Issue by aidooyaw1992** [renefloor/flutter_cache_manager#84]
i keep getting this issue when running on emulator

E/flutter ( 4601): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter ( 4601): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:300
E/flutter ( 4601): <asynchronous suspension>
E/flutter ( 4601): #1      invokeMethod (package:sqflite/src/sqflite_impl.dart:18:34)
E/flutter ( 4601): <asynchronous suspension>
E/flutter ( 4601): #2      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:33:7)
E/flutter ( 4601): #3      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite/src/factory_mixin.dart:22:35)
E/flutter ( 4601): #4      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:34)
E/flutter ( 4601): <asynchronous suspension>
E/flutter ( 4601): #5      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29:7)
E/flutter ( 4601): #6      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite/src/factory_mixin.dart:22:7)
E/flutter ( 4601): #7      _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite/src/factory_mixin.dart:136:17)
E/flutter ( 4601): <asynchronous suspension>
E/flutter ( 4601): #8      getDatabasesPath (package:sqflite/sqflite.dart:162:54)
E/flutter ( 4601): #9      CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:32:31)
E/flutter ( 4601): <asynchronous suspension>
E/flutter ( 4601): #10     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:28:28)
E/flutter ( 4601): #11     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:64:17)
E/flutter ( 4601): #12     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:34:29)
E/flutter ( 4601): #13     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:29:23)
E/flutter ( 4601): #14     _CachePageState._downloadFile
package:new_ereader_bloc_app/screens/cache_page.dart:16
E/flutter ( 4601): #15     _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:511
E/flutter ( 4601): #16     _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:566
E/flutter ( 4601): #17     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:166
E/flutter ( 4601): #18     TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:240
E/flutter ( 4601): #19     TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:211
E/flutter ( 4601): #20     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter ( 4601): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:225
E/flutter ( 4601): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 4601): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter ( 4601): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter ( 4601): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter ( 4601): #26     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 4601): #27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 4601): #28     _CustomZone

**Comment by natancamenzind** [comment]
same here, but on physical devices as well

**Comment by renefloor** [comment]
Maybe something is wrong with the packages? Can you make sure you are using the latest version (1.1.0) and run flutter pub upgrade?

**Comment by selarom-epilef** [comment]
I'm also having this problem with v1.1.3
